spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb
    username: abstract-programmer
    password: example-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: server-app
